#! /usr/bin/python


# mf v0.5            22 July 2002        Edward d'Auvergne
#
# Program to process all model-free input and output.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


from re import match
import sys

from model_free import model_free
from palmer import palmer
from relax_fit import relax_fit

from data import data
from file_ops import file_ops

from interpreter import interpreter

sys.path.append(sys.path[0])
sys.path[0] = '.'
from usr_param import usr_param

from model_selection.model_selection import model_selection
from minimise.minimise import minimise

class mf:
	def __init__(self):
		"The top level class."

		self.version = 0.5
		self.set_intro_string()

		# Debugging option, 0 = off, 1 = on.
		self.debug = 0

		# Import the user parameters.
		self.usr_param = usr_param()
		if not self.version == self.usr_param.version:
			print "The versions numbers of the program and the file 'usr_param.py' do not match."
			print "Copy the correct version to the working directory, quitting program."
			sys.exit()

		# Initialise the class self.mf.function to place program functions into.
		self.data = data(self)
		self.file_ops = file_ops(self)
		self.model_selection = model_selection(self)
		self.minimise = minimise

		interpreter(self)
		sys.exit()

		# Select the behaviour of the program.
		if match('^[Rr]elax[- _][Ff]it$', self.usr_param.program_type):
			relax_fit(self)

		elif match('^[Mm][Ff]$', self.usr_param.program_type):
			model_free(self)

		elif match('^[Pp]almer$', self.usr_param.program_type):
			palmer(self)

		else:
			print "The program type " + `self.usr_param.program_type` + " does not exist."


	def set_intro_string(self):
		"Create the program introduction."

		self.intro_string = """

		                      mf v0.5

		Program to process all model-free input and output.

		"""


if __name__ == "__main__":
	mf()
