#! /data03/dauvergne/bin/python
# /usr/bin/python


# modelfree.py   v0.1            31 October 2001        Edward d'Auvergne
#
# Program to process all modelfree input and output.
#
# Input data is specified in the file "input". An example of the format of the file is:
#
#	$ cat ./input
#	NMR_frq_label 600
#	NMR_frq       599.741
#	R1            R1.600.out
#	R2            R2.600.out
#	NOE           noe.600.out
#	
#	NMR_frq_label 500
#	NMR_frq       500.241
#	R1            R1.500.out
#	R2            none
#	NOE           noe.500.out
#
#
# The script is divided into the three stages of model selection:
#
#	Stage 1:   Creation of the files for the modelfree calculations for models 1 to 5,
#		and f-tests between them.
#	Stage 2:   Model selection and creation of the final optimization run.  The modelfree
#		input files for optimization are placed into the directory "optimize".
#	Stage 3:   Extraction of optimized data.

import sys
from re import match

from data import data
from file_ops import file_ops
from star import star

sys.path.append('.')
from usr_param import usr_param

from asymptotic import asymptotic
from palmer import palmer
from true import true


class mf:
	def __init__(self):
		"The top level class."

		self.data = data()
		self.data.usr_param = usr_param()
		self.file_ops = file_ops(self)
		self.star = star()

		self.print_header()

		if match('^AIC$', self.data.usr_param.method):
			asymptotic(self)
		elif match('^AICc$', self.data.usr_param.method):
			asymptotic(self)
		elif match('^BIC$', self.data.usr_param.method):
			asymptotic(self)
		elif match('^Palmer$', self.data.usr_param.method):
			palmer(self)
		elif match('^True$', self.data.usr_param.method):
			true(self)
		else:
			print "The modelfree analysis method is not set correctly.  Check self.method in"
			print "the file 'usr_param.py' which should be in the working directory."
			print "Quitting script!"
			sys.exit()
			


	def print_header(self):
		"Print the header to screen."

		print """

		              Modelfree.py v0.1

		Program to process all modelfree input and output.
		
		"""


if __name__ == "__main__":
	mf()
