#! /usr/bin/python

###############################################################################
#                                                                             #
#                                    relax                                    #
#                                                                             #
#                   a program for relaxation data analysis                    #
#                                                                             #
#                             by Edward d'Auvergne                            #
#                                                                             #
###############################################################################
#                                                                             #
#                                   License                                   #
#                                                                             #
# relax, a program for relaxation data analysis.                              #
#                                                                             #
# Copyright (C) 2003 Edward d'Auvergne                                        #
#                                                                             #
# This program is free software; you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation; either version 2 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU Library General Public License for more details.                        #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program; if not, write to the Free Software                 #
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  #
#                                                                             #
###############################################################################


from os import F_OK, access
import profile
import pstats
from re import match
import sys
try:
    import Numeric
except ImportError:
    print "The python package Numeric cannot be found."
    sys.exit()

from data import Data
from file_ops import File_ops
from diffusion_tensor import Diffusion_tensor
from dx.map import Map
from dx.opendx import OpenDX
from load import Load
from min import Minimise
from model_free import Model_free
from model_selection.model_selection import Model_selection
from palmer import Palmer
from prompt.interpreter import Interpreter
from read import Read
from relax_fit import Relax_fit
from specific_setup import Specific_setup
from state import State
from value import Value
from write import Write

sys.path.append(sys.path[0])
sys.path[0] = '.'


class Relax:
    def __init__(self, argv):
        """The top level class."""

        self.argv = argv

        # Create a string to pass to the interpreter to print.
        self.set_intro_string()

        # Debugging option, 0 = off, 1 = on.
        self.debug = 0

        # The program data storage class.
        self.data = Data()

        # Various functions.
        self.diffusion_tensor = Diffusion_tensor(self)
        self.file_ops = File_ops(self)
        self.load = Load(self)
        self.map = Map(self)
        self.min = Minimise(self)
        #self.model_selection = Model_selection(self)
        self.model_free = Model_free(self)
        self.opendx = OpenDX(self)
        self.read = Read(self)
        self.specific_setup = Specific_setup(self)
        self.state = State(self)
        self.value = Value(self)
        self.write = Write(self)

        # Process the command line arguments.
        self.arguments()

        # Run the interpreter.
        self.interpreter = Interpreter(self)
        self.interpreter.run()


    def arguments(self):
        """Function for processing the command line arguments."""

        # Initialise.
        self.script_file = None

        # No arguments are given.
        if len(self.argv) == 1:
            return

        # Help.
        elif match('--help', self.argv[1]) or match('-h', self.argv[1]):
            self.print_help()
            sys.exit()

        # Script file.
        elif type(self.argv[1]) == str and len(self.argv) == 2:
            self.script_file = self.argv[1]
            if not access(self.script_file, F_OK):
                sys.stderr.write("The script file '" + self.script_file + "' does not exist.\n")
                sys.exit()

        # Unknown argument.
        else:
            print "Try \"relax --help\" for more information."
            sys.exit()


    def print_help(self):
        """Print the help message."""

        sys.stderr.write("\nUsage: relax [-h] [--help] [script]\n")
        sys.stderr.write("Options:\n")
        sys.stderr.write("   --help       Display this help and exit.\n\n")


    def set_intro_string(self):
        """Create the program introduction."""

        self.intro_string = """


                                            relax

                           a program for relaxation data analysis

                            Copyright (C) 2003 Edward d'Auvergne


This is free software which you are welcome to modify and redistribute under the conditions of the
GNU General Public License (GPL).  This program, including all modules, is licensed under the GPL
and comes with absolutely no warranty.  For details type GPL.
"""



if __name__ == "__main__":
    # Change this flag to 1 for code profiling.
    profile_flag = 0

    if not profile_flag:
        Relax(sys.argv)
    else:
        def print_stats(stats):
            pstats.Stats(stats).sort_stats(-1).print_stats()

        profile.Profile.print_stats = print_stats
        profile.run('Relax(sys.argv)')
