#! /usr/bin/python
# That line was just so programs like gvim or emacs will understand that this is Python code!  Don't
# make this file executable.

###############################################################################
#                                                                             #
# Copyright (C) 2006 Edward d'Auvergne                                        #
#                                                                             #
# This file is part of the program relax.                                     #
#                                                                             #
# relax is free software; you can redistribute it and/or modify               #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation; either version 2 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# relax is distributed in the hope that it will be useful,                    #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with relax; if not, write to the Free Software                        #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA   #
#                                                                             #
###############################################################################


# Import statements.
import sys


# Construct the python include path (for Python.h).
py_include_path = sys.prefix + '/include/python' + `sys.version_info[0]` + '.' + `sys.version_info[1]`


# C flags.
cflags = '-I' + py_include_path


# File names.
relax_fit_files = ['maths_fns/c_chi2.c',
                   'maths_fns/exponential.c',
                   'maths_fns/relax_fit.c']

# Loop over the relaxation curve fitting files.
relax_fit_nodes = []
for file in relax_fit_files:
    relax_fit_nodes.append(SharedObject(file, CCFLAGS=cflags, CPPPATH='maths_fns'))

# Build the relaxation curve fitting module.
relax_fit_object = SharedLibrary(target='maths_fns/relax_fit', source=relax_fit_nodes, SHLIBPREFIX='')
SourceSignatures('timestamp')



# Print out.
print "Building the relaxation curve fitting module " + `str(relax_fit_object[0])`
