###############################################################################
#                                                                             #
# Copyright (C) 2009 Michael Bieri                                            #
# Copyright (C) 2010 Edward d'Auvergne                                        #
#                                                                             #
# This file is part of the program relax.                                     #
#                                                                             #
# relax is free software; you can redistribute it and/or modify               #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation; either version 2 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# relax is distributed in the hope that it will be useful,                    #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with relax; if not, write to the Free Software                        #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA   #
#                                                                             #
###############################################################################

# Module docstring.
"""Module containing the base class for the automatic R1 and R2 analysis frames."""

# Python module imports.
from os import sep
import wx

# relax module imports.
from data import Relax_data_store; ds = Relax_data_store()

# relaxGUI module imports.
from analyses.project import open_file
from derived_wx_classes import StructureTextCtrl
from filedialog import multi_openfile, opendir
from message import exec_relax



class Auto_rx:
    """The base class for the R1 and R2 frames."""

    # Hardcoded variables.
    analysis_type = None
    bitmap = None
    label = None

    def __init__(self, gui):
        """Build the automatic R1 and R2 analysis GUI frame elements.

        @param gui: The main GUI class.
        @type gui:  gui_bieri.relax_gui.Main instance
        """

        self.gui = gui

        # Generate a storage container in the relax data store, and alias it for easy access.
        self.data = ds.relax_gui.analyses.add(self.analysis_type)

        # Build and pack the main sizer box, then add it to the automatic model-free analysis frame.
        main_box = self.build_main_box()
        self.gui.modelfree.SetSizer(main_box)

        # Set the frame font size.
        self.gui.modelfree.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))

        # R1 no. 1
        rx_data = ds.relax_gui.analyses[self.r1_index[0]]
        self.bitmap_1_copy_copy = wx.StaticBitmap(self.r1_1, -1, wx.Bitmap(IMAGE_PATH+'r1.png', wx.BITMAP_TYPE_ANY))
        self.label_4_copy_copy = wx.StaticText(self.r1_1, -1, "Set-up for R1 relaxation analysis:")
        self.label_2_copy_copy_copy_2_copy = wx.StaticText(self.r1_1, -1, "NMR Frequency [MHz]:", style=wx.ALIGN_RIGHT)
        self.nmrfreq_value_r11 = wx.TextCtrl(self.r1_1, -1, str(rx_data.frq))
        self.label_2_copy_copy_3_copy_copy = wx.StaticText(self.r1_1, -1, "Results directory", style=wx.ALIGN_RIGHT)
        self.resultsdir_r11 = wx.TextCtrl(self.r1_1, -1, rx_data.save_dir)
        self.results_directory_copy_copy = wx.Button(self.r1_1, -1, "Change")
        self.structure_file = wx.StaticText(self.r1_1, -1, "Structure file (.pdb)", style=wx.ALIGN_RIGHT)
        self.structure_r11 = StructureTextCtrl(self.r1_1, -1, self.structure_file_pdb_msg)
        self.structure_r11.SetEditable(False)
        self.results_directory_copy_copy_copy = wx.Button(self.r1_1, -1, "Change")
        self.label_2_copy_copy_copy_2_copy_copy = wx.StaticText(self.r1_1, -1, "Unresolved residues:", style=wx.ALIGN_RIGHT)
        self.unresolved_r11 = wx.TextCtrl(self.r1_1, -1, "")
        self.panel_2 = wx.Panel(self.r1_1, -1)
        self.addr11 = wx.Button(self.panel_1, -1, "add")
        self.refreshr11 = wx.Button(self.panel_1, -1, "refresh")
        self.label_3 = wx.StaticText(self.panel_3, -1, "R1 relaxation peak list                                                              ")
        self.label_6 = wx.StaticText(self.panel_3, -1, "Relaxation time [s]")
        self.r1_list_1 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_1 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_2 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_2 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_3 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_3 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_4 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_4 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_5 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_5 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_6 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_6 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_7 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_7 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_8 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_8 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_9 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_9 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_10 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_10 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_11 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_11 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_12 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_12 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_1_copy_11 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_13 = wx.TextCtrl(self.panel_3, -1, "")
        self.r1_list_14 = wx.StaticText(self.panel_3, -1, "")
        self.r1_time_1_4 = wx.TextCtrl(self.panel_3, -1, "")
        self.label_5_copy_1_copy = wx.StaticText(self.r1_1, -1, "Execute relax        ", style=wx.ALIGN_RIGHT)
        self.relax_start_r1_1 = wx.BitmapButton(self.r1_1, -1, wx.Bitmap(IMAGE_PATH+'relax_start.gif', wx.BITMAP_TYPE_ANY))

        #button actions
        self.Bind(wx.EVT_BUTTON, self.resdir_r1_1, self.results_directory_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.structure_r11.open_file, self.results_directory_copy_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.add_r1_1, self.addr11)
        self.Bind(wx.EVT_BUTTON, self.refresh_r1_1, self.refreshr11)


    def __do_layout(self):
        # begin wxGlade: main.__do_layout
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_22_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_23_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_23_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17_copy_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_19_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_19_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19_copy = wx.BoxSizer(wx.HORIZONTAL)
        frq1sub_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_copy_1 = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1_copy_copy_1 = wx.FlexGridSizer(10, 2, 0, 0)
        sizer_13_copy_copy_1 = wx.BoxSizer(wx.VERTICAL)
        nmr_freq_copy_copy_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_copy_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_2 = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1_copy_2 = wx.FlexGridSizer(10, 2, 0, 0)
        sizer_13_copy_2 = wx.BoxSizer(wx.VERTICAL)
        nmr_freq_copy_copy_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_3 = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_copy_copy_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy_1_copy_1 = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        unresolved_resi_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        pdbfile_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8_copy_copy_copy_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        noe_ref_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        noe_sat_err_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        noe_sat_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        frq1sub_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_copy = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1_copy_copy = wx.FlexGridSizer(10, 2, 0, 0)
        sizer_13_copy_copy = wx.BoxSizer(wx.VERTICAL)
        nmr_freq_copy_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_copy_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy_1 = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1_copy_1 = wx.FlexGridSizer(10, 2, 0, 0)
        sizer_13_copy_1 = wx.BoxSizer(wx.VERTICAL)
        nmr_freq_copy_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_copy_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy_1_copy = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        unresolved_resi_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        pdbfile_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8_copy_copy_copy_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        noe_ref_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        noe_sat_err_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        noe_sat_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        frq1sub = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11_copy = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12_copy = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1_copy = wx.FlexGridSizer(10, 2, 0, 0)
        sizer_13_copy = wx.BoxSizer(wx.VERTICAL)
        nmr_freq_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(10, 2, 0, 0)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        nmr_freq_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy_1 = wx.BoxSizer(wx.VERTICAL)
        exec_relax_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        results_dir_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        unresolved_resi_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        pdbfile_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8_copy_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        noe_ref_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        noe_sat_err_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        noe_sat_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        nmr_freq_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1.Add(self.bitmap_1_copy_1, 0, wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1.Add(self.label_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_1.Add(self.label_2_copy_copy_copy_3, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_1.Add(self.nmrfreq_value_noe1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1.Add(nmr_freq_copy_1, 1, wx.EXPAND, 0)
        noe_sat_copy_1.Add(self.label_2_copy_copy_5, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_copy_1.Add(self.noe_sat_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_copy_1.Add(self.sat_noe_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1.Add(noe_sat_copy_1, 1, wx.EXPAND, 0)
        noe_sat_err_copy_1.Add(self.label_2_copy_copy_copy_copy_2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_err_copy_1.Add(self.noe_sat_err_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1.Add(noe_sat_err_copy_1, 1, wx.EXPAND, 0)
        noe_ref_copy_1.Add(self.label_2_copy_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_ref_copy_1.Add(self.noe_ref_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_ref_copy_1.Add(self.noe_ref_err_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1.Add(noe_ref_copy_1, 1, wx.EXPAND, 0)
        sizer_8_copy_copy_copy_copy_1.Add(self.label_2_copy_copy_copy_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_8_copy_copy_copy_copy_1.Add(self.noe_ref_err_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1.Add(sizer_8_copy_copy_copy_copy_1, 1, wx.EXPAND, 0)
        pdbfile_copy_1.Add(self.label_2_copy_copy_2_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        pdbfile_copy_1.Add(self.structure_noe1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        pdbfile_copy_1.Add(self.ref_noe_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1.Add(pdbfile_copy_1, 1, wx.EXPAND, 0)
        unresolved_resi_copy_1.Add(self.label_2_copy_copy_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        unresolved_resi_copy_1.Add(self.unres_noe1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1.Add(unresolved_resi_copy_1, 1, wx.EXPAND, 0)
        results_dir_copy_1.Add(self.label_2_copy_copy_3_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_1.Add(self.res_noe1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_1.Add(self.chandir_noe1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1.Add(results_dir_copy_1, 1, wx.EXPAND, 0)
        sizer_2_copy_1.Add(self.label_2_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1.Add(sizer_2_copy_1, 1, wx.EXPAND, 0)
        exec_relax_copy_1.Add(self.label_5_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1.Add(self.relax_start_noe1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1.Add(exec_relax_copy_1, 1, wx.ALIGN_RIGHT, 0)
        sizer_5_copy_1.Add(sizer_6_copy_1, 1, wx.EXPAND|wx.SHAPED, 0)
        self.noe1.SetSizer(sizer_5_copy_1)
        sizer_10.Add(self.bitmap_1_copy_copy, 0, wx.ADJUST_MINSIZE, 10)
        sizer_11.Add(self.label_4_copy_copy, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 18)
        nmr_freq_copy_copy.Add(self.label_2_copy_copy_copy_2_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy.Add(self.nmrfreq_value_r11, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(nmr_freq_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        results_dir_copy_copy.Add(self.label_2_copy_copy_3_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy.Add(self.resultsdir_r11, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy.Add(self.results_directory_copy_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11.Add(results_dir_copy_copy, 1, wx.EXPAND, 0)
        results_dir_copy_copy_copy.Add(self.structure_file, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy.Add(self.structure_r11, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy.Add(self.results_directory_copy_copy_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11.Add(results_dir_copy_copy_copy, 1, wx.EXPAND, 0)
        nmr_freq_copy_copy_copy.Add(self.label_2_copy_copy_copy_2_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy.Add(self.unresolved_r11, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(nmr_freq_copy_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_11.Add(self.panel_2, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_13.Add(self.addr11, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.refreshr11, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12.Add(sizer_13, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_9, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_9, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_11, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_11, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_12, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_12, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_1_copy_11, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_13, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_list_14, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.r1_time_1_4, 0, wx.ADJUST_MINSIZE, 0)
        self.panel_3.SetSizer(grid_sizer_1)
        sizer_12.Add(self.panel_3, 0, wx.EXPAND|wx.SHAPED, 0)
        self.panel_1.SetSizer(sizer_12)
        sizer_11.Add(self.panel_1, 0, wx.EXPAND|wx.SHAPED, 0)
        exec_relax_copy_1_copy.Add(self.label_5_copy_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy.Add(self.relax_start_r1_1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(exec_relax_copy_1_copy, 0, wx.ALIGN_RIGHT, 0)
        sizer_10.Add(sizer_11, 0, 0, 0)
        self.r1_1.SetSizer(sizer_10)
        sizer_10_copy.Add(self.bitmap_1_copy_copy_copy, 0, wx.ADJUST_MINSIZE, 10)
        sizer_11_copy.Add(self.label_4_copy_copy_copy, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 18)
        nmr_freq_copy_copy_copy_1.Add(self.label_2_copy_copy_copy_2_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_1.Add(self.nmrfreq_value_r21, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy.Add(nmr_freq_copy_copy_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        results_dir_copy_copy_copy_1.Add(self.label_2_copy_copy_3_copy_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_1.Add(self.resultsdir_r21, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_1.Add(self.results_directory_r21, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy.Add(results_dir_copy_copy_copy_1, 1, wx.EXPAND, 0)
        results_dir_copy_copy_copy_copy.Add(self.structure_file_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy.Add(self.structure_r21, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy.Add(self.chan_struc_r21, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy.Add(results_dir_copy_copy_copy_copy, 1, wx.EXPAND, 0)
        nmr_freq_copy_copy_copy_copy.Add(self.label_2_copy_copy_copy_2_copy_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_copy.Add(self.unresolved_r21, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy.Add(nmr_freq_copy_copy_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_11_copy.Add(self.panel_2_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_13_copy.Add(self.addr21, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13_copy.Add(self.refreshr21, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12_copy.Add(sizer_13_copy, 1, wx.EXPAND, 0)
        grid_sizer_1_copy.Add(self.label_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_9, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_9, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_11, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_11, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_12, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_12, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_13, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_13, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_list_14, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.r2_time_14, 0, wx.ADJUST_MINSIZE, 0)
        self.panel_3_copy.SetSizer(grid_sizer_1_copy)
        sizer_12_copy.Add(self.panel_3_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        self.panel_1_copy.SetSizer(sizer_12_copy)
        sizer_11_copy.Add(self.panel_1_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        exec_relax_copy_1_copy_copy.Add(self.label_5_copy_1_copy_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_copy.Add(self.relax_start_r1_1_copy, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy.Add(exec_relax_copy_1_copy_copy, 0, wx.ALIGN_RIGHT, 0)
        sizer_10_copy.Add(sizer_11_copy, 0, 0, 0)
        self.r2_1.SetSizer(sizer_10_copy)
        self.notebook_3.AddPage(self.noe1, "steady-state NOE")
        self.notebook_3.AddPage(self.r1_1, "R1 relaxation")
        self.notebook_3.AddPage(self.r2_1, "R2 relaxation")
        frq1sub.Add(self.notebook_3, 1, wx.EXPAND, 0)
        self.frq1.SetSizer(frq1sub)
        sizer_5_copy_1_copy.Add(self.bitmap_1_copy_1_copy, 0, wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy.Add(self.label_4_copy_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_1_copy.Add(self.label_2_copy_copy_copy_3_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_1_copy.Add(self.nmrfreq_value_noe1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy.Add(nmr_freq_copy_1_copy, 1, wx.EXPAND, 0)
        noe_sat_copy_1_copy.Add(self.label_2_copy_copy_5_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_copy_1_copy.Add(self.noe_sat_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_copy_1_copy.Add(self.sat_noe_copy_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy.Add(noe_sat_copy_1_copy, 1, wx.EXPAND, 0)
        noe_sat_err_copy_1_copy.Add(self.label_2_copy_copy_copy_copy_2_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_err_copy_1_copy.Add(self.noe_sat_err_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy.Add(noe_sat_err_copy_1_copy, 1, wx.EXPAND, 0)
        noe_ref_copy_1_copy.Add(self.label_2_copy_copy_1_copy_1_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_ref_copy_1_copy.Add(self.noe_ref_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_ref_copy_1_copy.Add(self.noe_ref_err_copy_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy.Add(noe_ref_copy_1_copy, 1, wx.EXPAND, 0)
        sizer_8_copy_copy_copy_copy_1_copy.Add(self.label_2_copy_copy_copy_copy_copy_1_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_8_copy_copy_copy_copy_1_copy.Add(self.noe_ref_err_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy.Add(sizer_8_copy_copy_copy_copy_1_copy, 1, wx.EXPAND, 0)
        pdbfile_copy_1_copy.Add(self.label_2_copy_copy_2_copy_1_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        pdbfile_copy_1_copy.Add(self.structure_noe1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        pdbfile_copy_1_copy.Add(self.ref_noe_copy_1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy.Add(pdbfile_copy_1_copy, 1, wx.EXPAND, 0)
        unresolved_resi_copy_1_copy.Add(self.label_2_copy_copy_copy_1_copy_1_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        unresolved_resi_copy_1_copy.Add(self.unres_noe1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy.Add(unresolved_resi_copy_1_copy, 1, wx.EXPAND, 0)
        results_dir_copy_1_copy.Add(self.label_2_copy_copy_3_copy_1_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_1_copy.Add(self.res_noe1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_1_copy.Add(self.chandir_noe1_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy.Add(results_dir_copy_1_copy, 1, wx.EXPAND, 0)
        sizer_2_copy_1_copy.Add(self.label_2_copy_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy.Add(sizer_2_copy_1_copy, 1, wx.EXPAND, 0)
        exec_relax_copy_1_copy_1.Add(self.label_5_copy_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_1.Add(self.relax_start_noe1_copy, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy.Add(exec_relax_copy_1_copy_1, 1, wx.ALIGN_RIGHT, 0)
        sizer_5_copy_1_copy.Add(sizer_6_copy_1_copy, 1, wx.EXPAND|wx.SHAPED, 0)
        self.noe1_copy.SetSizer(sizer_5_copy_1_copy)
        sizer_10_copy_1.Add(self.bitmap_1_copy_copy_copy_1, 0, wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_1.Add(self.label_4_copy_copy_copy_1, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 18)
        nmr_freq_copy_copy_copy_2.Add(self.label_2_copy_copy_copy_2_copy_copy_2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_2.Add(self.nmrfreq_value_r11_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_1.Add(nmr_freq_copy_copy_copy_2, 0, wx.EXPAND|wx.SHAPED, 0)
        results_dir_copy_copy_copy_2.Add(self.label_2_copy_copy_3_copy_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_2.Add(self.resultsdir_r11_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_2.Add(self.results_directory_copy_copy_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_1.Add(results_dir_copy_copy_copy_2, 1, wx.EXPAND, 0)
        results_dir_copy_copy_copy_copy_1.Add(self.structure_file_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_1.Add(self.structure_r11_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_1.Add(self.results_directory_copy_copy_copy_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_1.Add(results_dir_copy_copy_copy_copy_1, 1, wx.EXPAND, 0)
        nmr_freq_copy_copy_copy_copy_1.Add(self.label_2_copy_copy_copy_2_copy_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_copy_1.Add(self.unresolved_r11_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_1.Add(nmr_freq_copy_copy_copy_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_11_copy_1.Add(self.panel_2_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_13_copy_1.Add(self.addr11_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13_copy_1.Add(self.refreshr11_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12_copy_1.Add(sizer_13_copy_1, 1, wx.EXPAND, 0)
        grid_sizer_1_copy_1.Add(self.label_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.label_6_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_5_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_5_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_7_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_7_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_8_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_8_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_9_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_9_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_10_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_10_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_11_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_11_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_12_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_12_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_1_copy_11_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_13_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_list_14_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_1.Add(self.r1_time_1_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        self.panel_3_copy_1.SetSizer(grid_sizer_1_copy_1)
        sizer_12_copy_1.Add(self.panel_3_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        self.panel_1_copy_1.SetSizer(sizer_12_copy_1)
        sizer_11_copy_1.Add(self.panel_1_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        exec_relax_copy_1_copy_copy_1.Add(self.label_5_copy_1_copy_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_copy_1.Add(self.relax_start_r1_1_copy_1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_1.Add(exec_relax_copy_1_copy_copy_1, 0, wx.ALIGN_RIGHT, 0)
        sizer_10_copy_1.Add(sizer_11_copy_1, 0, 0, 0)
        self.r1_1_copy.SetSizer(sizer_10_copy_1)
        sizer_10_copy_copy.Add(self.bitmap_1_copy_copy_copy_copy, 0, wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_copy.Add(self.label_4_copy_copy_copy_copy, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 18)
        nmr_freq_copy_copy_copy_1_copy.Add(self.label_2_copy_copy_copy_2_copy_copy_1_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_1_copy.Add(self.nmrfreq_value_r21_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_copy.Add(nmr_freq_copy_copy_copy_1_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        results_dir_copy_copy_copy_1_copy.Add(self.label_2_copy_copy_3_copy_copy_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_1_copy.Add(self.resultsdir_r21_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_1_copy.Add(self.results_directory_r21_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_copy.Add(results_dir_copy_copy_copy_1_copy, 1, wx.EXPAND, 0)
        results_dir_copy_copy_copy_copy_copy.Add(self.structure_file_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_copy.Add(self.structure_r21_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_copy.Add(self.chan_struc_r21_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_copy.Add(results_dir_copy_copy_copy_copy_copy, 1, wx.EXPAND, 0)
        nmr_freq_copy_copy_copy_copy_copy.Add(self.label_2_copy_copy_copy_2_copy_copy_copy_copy, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_copy_copy.Add(self.unresolved_r21_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_copy.Add(nmr_freq_copy_copy_copy_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_11_copy_copy.Add(self.panel_2_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_13_copy_copy.Add(self.addr21_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13_copy_copy.Add(self.refreshr21_copy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12_copy_copy.Add(sizer_13_copy_copy, 1, wx.EXPAND, 0)
        grid_sizer_1_copy_copy.Add(self.label_3_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.label_6_copy_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_2_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_5_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_5_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_7_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_7_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_8_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_8_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_9_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_9_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_10_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_10_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_11_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_11_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_12_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_12_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_13_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_13_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_list_14_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.r2_time_14_copy, 0, wx.ADJUST_MINSIZE, 0)
        self.panel_3_copy_copy.SetSizer(grid_sizer_1_copy_copy)
        sizer_12_copy_copy.Add(self.panel_3_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        self.panel_1_copy_copy.SetSizer(sizer_12_copy_copy)
        sizer_11_copy_copy.Add(self.panel_1_copy_copy, 0, wx.EXPAND|wx.SHAPED, 0)
        exec_relax_copy_1_copy_copy_copy.Add(self.label_5_copy_1_copy_copy_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_copy_copy.Add(self.relax_start_r1_1_copy_copy, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_copy.Add(exec_relax_copy_1_copy_copy_copy, 0, wx.ALIGN_RIGHT, 0)
        sizer_10_copy_copy.Add(sizer_11_copy_copy, 0, 0, 0)
        self.r2_1_copy.SetSizer(sizer_10_copy_copy)
        self.notebook_3_copy.AddPage(self.noe1_copy, "steady-state NOE")
        self.notebook_3_copy.AddPage(self.r1_1_copy, "R1 relaxation")
        self.notebook_3_copy.AddPage(self.r2_1_copy, "R2 relaxation")
        frq1sub_copy.Add(self.notebook_3_copy, 1, wx.EXPAND, 0)
        self.frq2.SetSizer(frq1sub_copy)
        sizer_5_copy_1_copy_1.Add(self.bitmap_1_copy_1_copy_1, 0, wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy_1.Add(self.label_4_copy_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_1_copy_1.Add(self.label_2_copy_copy_copy_3_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_1_copy_1.Add(self.nmrfreq_value_noe1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy_1.Add(nmr_freq_copy_1_copy_1, 1, wx.EXPAND, 0)
        noe_sat_copy_1_copy_1.Add(self.label_2_copy_copy_5_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_copy_1_copy_1.Add(self.noe_sat_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_copy_1_copy_1.Add(self.sat_noe_copy_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy_1.Add(noe_sat_copy_1_copy_1, 1, wx.EXPAND, 0)
        noe_sat_err_copy_1_copy_1.Add(self.label_2_copy_copy_copy_copy_2_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_sat_err_copy_1_copy_1.Add(self.noe_sat_err_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy_1.Add(noe_sat_err_copy_1_copy_1, 1, wx.EXPAND, 0)
        noe_ref_copy_1_copy_1.Add(self.label_2_copy_copy_1_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_ref_copy_1_copy_1.Add(self.noe_ref_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        noe_ref_copy_1_copy_1.Add(self.noe_ref_err_copy_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy_1.Add(noe_ref_copy_1_copy_1, 1, wx.EXPAND, 0)
        sizer_8_copy_copy_copy_copy_1_copy_1.Add(self.label_2_copy_copy_copy_copy_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_8_copy_copy_copy_copy_1_copy_1.Add(self.noe_ref_err_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy_1.Add(sizer_8_copy_copy_copy_copy_1_copy_1, 1, wx.EXPAND, 0)
        pdbfile_copy_1_copy_1.Add(self.label_2_copy_copy_2_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        pdbfile_copy_1_copy_1.Add(self.structure_noe1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        pdbfile_copy_1_copy_1.Add(self.ref_noe_copy_1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy_1.Add(pdbfile_copy_1_copy_1, 1, wx.EXPAND, 0)
        unresolved_resi_copy_1_copy_1.Add(self.label_2_copy_copy_copy_1_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        unresolved_resi_copy_1_copy_1.Add(self.unres_noe1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy_1.Add(unresolved_resi_copy_1_copy_1, 1, wx.EXPAND, 0)
        results_dir_copy_1_copy_1.Add(self.label_2_copy_copy_3_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_1_copy_1.Add(self.res_noe1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_1_copy_1.Add(self.chandir_noe1_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6_copy_1_copy_1.Add(results_dir_copy_1_copy_1, 1, wx.EXPAND, 0)
        sizer_2_copy_1_copy_1.Add(self.label_2_copy_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy_1.Add(sizer_2_copy_1_copy_1, 1, wx.EXPAND, 0)
        exec_relax_copy_1_copy_2.Add(self.label_5_copy_1_copy_2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_2.Add(self.relax_start_noe1_copy_1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_6_copy_1_copy_1.Add(exec_relax_copy_1_copy_2, 1, wx.ALIGN_RIGHT, 0)
        sizer_5_copy_1_copy_1.Add(sizer_6_copy_1_copy_1, 1, wx.EXPAND|wx.SHAPED, 0)
        self.noe1_copy_1.SetSizer(sizer_5_copy_1_copy_1)
        sizer_10_copy_2.Add(self.bitmap_1_copy_copy_copy_2, 0, wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_2.Add(self.label_4_copy_copy_copy_2, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 18)
        nmr_freq_copy_copy_copy_3.Add(self.label_2_copy_copy_copy_2_copy_copy_3, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_3.Add(self.nmrfreq_value_r11_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_2.Add(nmr_freq_copy_copy_copy_3, 0, wx.EXPAND|wx.SHAPED, 0)
        results_dir_copy_copy_copy_3.Add(self.label_2_copy_copy_3_copy_copy_copy_2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_3.Add(self.resultsdir_r11_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_3.Add(self.results_directory_copy_copy_copy_2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_2.Add(results_dir_copy_copy_copy_3, 1, wx.EXPAND, 0)
        results_dir_copy_copy_copy_copy_2.Add(self.structure_file_copy_2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_2.Add(self.structure_r11_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_2.Add(self.results_directory_copy_copy_copy_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_2.Add(results_dir_copy_copy_copy_copy_2, 1, wx.EXPAND, 0)
        nmr_freq_copy_copy_copy_copy_2.Add(self.label_2_copy_copy_copy_2_copy_copy_copy_2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_copy_2.Add(self.unresolved_r11_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_2.Add(nmr_freq_copy_copy_copy_copy_2, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_11_copy_2.Add(self.panel_2_copy_2, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_13_copy_2.Add(self.addr11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13_copy_2.Add(self.refreshr11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12_copy_2.Add(sizer_13_copy_2, 1, wx.EXPAND, 0)
        grid_sizer_1_copy_2.Add(self.label_3_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.label_6_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_5_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_5_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_6_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_6_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_7_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_7_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_8_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_8_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_9_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_9_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_10_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_10_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_12_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_12_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_1_copy_11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_13_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_list_14_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_2.Add(self.r1_time_1_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        self.panel_3_copy_2.SetSizer(grid_sizer_1_copy_2)
        sizer_12_copy_2.Add(self.panel_3_copy_2, 0, wx.EXPAND|wx.SHAPED, 0)
        self.panel_1_copy_2.SetSizer(sizer_12_copy_2)
        sizer_11_copy_2.Add(self.panel_1_copy_2, 0, wx.EXPAND|wx.SHAPED, 0)
        exec_relax_copy_1_copy_copy_2.Add(self.label_5_copy_1_copy_copy_2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_copy_2.Add(self.relax_start_r1_1_copy_2, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_2.Add(exec_relax_copy_1_copy_copy_2, 0, wx.ALIGN_RIGHT, 0)
        sizer_10_copy_2.Add(sizer_11_copy_2, 0, 0, 0)
        self.r1_1_copy_1.SetSizer(sizer_10_copy_2)
        sizer_10_copy_copy_1.Add(self.bitmap_1_copy_copy_copy_copy_1, 0, wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_copy_1.Add(self.label_4_copy_copy_copy_copy_1, 0, wx.BOTTOM|wx.ADJUST_MINSIZE, 18)
        nmr_freq_copy_copy_copy_1_copy_1.Add(self.label_2_copy_copy_copy_2_copy_copy_1_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_1_copy_1.Add(self.nmrfreq_value_r21_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_copy_1.Add(nmr_freq_copy_copy_copy_1_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        results_dir_copy_copy_copy_1_copy_1.Add(self.label_2_copy_copy_3_copy_copy_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_1_copy_1.Add(self.resultsdir_r21_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_1_copy_1.Add(self.results_directory_r21_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_copy_1.Add(results_dir_copy_copy_copy_1_copy_1, 1, wx.EXPAND, 0)
        results_dir_copy_copy_copy_copy_copy_1.Add(self.structure_file_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_copy_1.Add(self.structure_r21_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        results_dir_copy_copy_copy_copy_copy_1.Add(self.chan_struc_r21_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_11_copy_copy_1.Add(results_dir_copy_copy_copy_copy_copy_1, 1, wx.EXPAND, 0)
        nmr_freq_copy_copy_copy_copy_copy_1.Add(self.label_2_copy_copy_copy_2_copy_copy_copy_copy_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        nmr_freq_copy_copy_copy_copy_copy_1.Add(self.unresolved_r21_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_copy_1.Add(nmr_freq_copy_copy_copy_copy_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_11_copy_copy_1.Add(self.panel_2_copy_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        sizer_13_copy_copy_1.Add(self.addr21_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13_copy_copy_1.Add(self.refreshr21_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12_copy_copy_1.Add(sizer_13_copy_copy_1, 1, wx.EXPAND, 0)
        grid_sizer_1_copy_copy_1.Add(self.label_3_copy_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.label_6_copy_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_2_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_3_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_4_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_5_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_5_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_6_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_6_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_7_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_7_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_8_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_8_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_9_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_9_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_10_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_10_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_11_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_12_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_12_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_13_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_13_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_list_14_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy_1.Add(self.r2_time_14_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        self.panel_3_copy_copy_1.SetSizer(grid_sizer_1_copy_copy_1)
        sizer_12_copy_copy_1.Add(self.panel_3_copy_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        self.panel_1_copy_copy_1.SetSizer(sizer_12_copy_copy_1)
        sizer_11_copy_copy_1.Add(self.panel_1_copy_copy_1, 0, wx.EXPAND|wx.SHAPED, 0)
        exec_relax_copy_1_copy_copy_copy_1.Add(self.label_5_copy_1_copy_copy_copy_1, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        exec_relax_copy_1_copy_copy_copy_1.Add(self.relax_start_r1_1_copy_copy_1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 0)
        sizer_11_copy_copy_1.Add(exec_relax_copy_1_copy_copy_copy_1, 0, wx.ALIGN_RIGHT, 0)
        sizer_10_copy_copy_1.Add(sizer_11_copy_copy_1, 0, 0, 0)
        self.r2_1_copy_1.SetSizer(sizer_10_copy_copy_1)
        self.notebook_3_copy_1.AddPage(self.noe1_copy_1, "steady-state NOE")
        self.notebook_3_copy_1.AddPage(self.r1_1_copy_1, "R1 relaxation")
        self.notebook_3_copy_1.AddPage(self.r2_1_copy_1, "R2 relaxation")
        frq1sub_copy_1.Add(self.notebook_3_copy_1, 1, wx.EXPAND, 0)
        self.frq3.SetSizer(frq1sub_copy_1)
        sizer_22.Add(self.label_11, 0, wx.LEFT|wx.ADJUST_MINSIZE, 10)
        sizer_23.Add(self.list_noe, 0, wx.ADJUST_MINSIZE, 0)
        sizer_23.Add(self.open_noe_results, 0, wx.ADJUST_MINSIZE, 0)
        sizer_22.Add(sizer_23, 1, wx.LEFT|wx.EXPAND, 10)
        sizer_9.Add(sizer_22, 1, wx.EXPAND, 0)
        sizer_22_copy.Add(self.label_11_copy, 0, wx.LEFT|wx.ADJUST_MINSIZE, 10)
        sizer_23_copy.Add(self.list_rx, 0, wx.ADJUST_MINSIZE, 0)
        sizer_23_copy.Add(self.open_rx_results, 0, wx.ADJUST_MINSIZE, 0)
        sizer_22_copy.Add(sizer_23_copy, 1, wx.LEFT|wx.EXPAND, 10)
        sizer_9.Add(sizer_22_copy, 1, wx.EXPAND, 0)
        sizer_22_copy_copy.Add(self.label_11_copy_copy, 0, wx.LEFT|wx.ADJUST_MINSIZE, 10)
        sizer_23_copy_copy.Add(self.list_modelfree, 0, wx.ADJUST_MINSIZE, 0)
        sizer_23_copy_copy.Add(self.open_model_results, 0, wx.ADJUST_MINSIZE, 0)
        sizer_22_copy_copy.Add(sizer_23_copy_copy, 1, wx.LEFT|wx.EXPAND, 10)
        sizer_9.Add(sizer_22_copy_copy, 1, wx.EXPAND, 0)
        self.results.SetSizer(sizer_9)
        self.notebook_2.AddPage(self.frq1, "Frq. 1")
        self.notebook_2.AddPage(self.frq2, "Frq. 2")
        self.notebook_2.AddPage(self.frq3, "Frq. 3")
        self.notebook_2.AddPage(self.modelfree, "Model-free")
        self.notebook_2.AddPage(self.results, "Results")
        sizer_8.Add(self.notebook_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_8)
        self.Layout()
        self.SetSize((1000, 600))
        self.Centre()


    def __set_properties(self):
        # begin wxGlade: main.__set_properties
        self.SetTitle("relaxGUI " + GUI_version)
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap(IMAGE_PATH+'relax.gif', wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((1000, 600))
        self.frame_1_statusbar.SetStatusWidths([800, 50, -1])
        # statusbar fields
        frame_1_statusbar_fields = ["relaxGUI (C) by Michael Bieri 2009", "relax:", version]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.label_4_copy_1.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_3.SetMinSize((230, 17))
        self.nmrfreq_value_noe1.SetMinSize((350, 27))
        self.label_2_copy_copy_5.SetMinSize((230, 17))
        self.noe_sat_1.SetMinSize((350, 27))
        self.sat_noe_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_copy_2.SetMinSize((230, 17))
        self.noe_sat_err_1.SetMinSize((350, 27))
        self.label_2_copy_copy_1_copy_1.SetMinSize((230, 17))
        self.noe_ref_1.SetMinSize((350, 27))
        self.noe_ref_err_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_copy_copy_1.SetMinSize((230, 17))
        self.noe_ref_err_1.SetMinSize((350, 27))
        self.label_2_copy_copy_2_copy_1.SetMinSize((230, 17))
        self.structure_noe1.SetMinSize((350, 27))
        self.ref_noe_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_1_copy_1.SetMinSize((230, 34))
        self.unres_noe1.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_1.SetMinSize((230, 17))
        self.res_noe1.SetMinSize((350, 27))
        self.chandir_noe1.SetMinSize((103, 27))
        self.label_5_copy_1.SetMinSize((118, 17))
        self.relax_start_noe1.SetName('hello')
        self.relax_start_noe1.SetSize(self.relax_start_noe1.GetBestSize())
        self.label_4_copy_copy.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_2_copy.SetMinSize((230, 17))
        self.nmrfreq_value_r11.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_copy.SetMinSize((230, 17))
        self.resultsdir_r11.SetMinSize((350, 27))
        self.results_directory_copy_copy.SetMinSize((103, 27))
        self.structure_file.SetMinSize((230, 17))
        self.structure_r11.SetMinSize((350, 27))
        self.results_directory_copy_copy_copy.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_2_copy_copy.SetMinSize((230, 17))
        self.unresolved_r11.SetMinSize((350, 27))
        self.panel_2.SetMinSize((688, 5))
        self.addr11.SetMinSize((60, 27))
        self.refreshr11.SetMinSize((60, 27))
        self.label_3.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.r1_time_1.SetMinSize((80, 20))
        self.r1_time_2.SetMinSize((80, 20))
        self.r1_time_3.SetMinSize((80, 20))
        self.r1_time_4.SetMinSize((80, 20))
        self.r1_time_5.SetMinSize((80, 20))
        self.r1_time_6.SetMinSize((80, 20))
        self.r1_time_7.SetMinSize((80, 20))
        self.r1_time_8.SetMinSize((80, 20))
        self.r1_time_9.SetMinSize((80, 20))
        self.r1_time_10.SetMinSize((80, 20))
        self.r1_time_11.SetMinSize((80, 20))
        self.r1_time_12.SetMinSize((80, 20))
        self.r1_time_13.SetMinSize((80, 20))
        self.r1_time_1_4.SetMinSize((80, 20))
        self.panel_3.SetMinSize((620, 300))
        self.panel_3.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1.SetMinSize((688, 300))
        self.panel_1.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_5_copy_1_copy.SetMinSize((118, 17))
        self.relax_start_r1_1.SetName('hello')
        self.relax_start_r1_1.SetSize(self.relax_start_r1_1.GetBestSize())
        self.label_4_copy_copy_copy.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_2_copy_copy_1.SetMinSize((230, 17))
        self.nmrfreq_value_r21.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_copy_copy.SetMinSize((230, 17))
        self.resultsdir_r21.SetMinSize((350, 27))
        self.results_directory_r21.SetMinSize((103, 27))
        self.structure_file_copy.SetMinSize((230, 17))
        self.structure_r21.SetMinSize((350, 27))
        self.chan_struc_r21.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_2_copy_copy_copy.SetMinSize((230, 17))
        self.unresolved_r21.SetMinSize((350, 27))
        self.panel_2_copy.SetMinSize((688, 5))
        self.addr21.SetMinSize((60, 27))
        self.refreshr21.SetMinSize((60, 27))
        self.label_3_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.r2_time_1.SetMinSize((80, 20))
        self.r2_time_2.SetMinSize((80, 20))
        self.r2_time_3.SetMinSize((80, 20))
        self.r2_time_4.SetMinSize((80, 20))
        self.r2_time_5.SetMinSize((80, 20))
        self.r2_time_6.SetMinSize((80, 20))
        self.r2_time_7.SetMinSize((80, 20))
        self.r2_time_8.SetMinSize((80, 20))
        self.r2_time_9.SetMinSize((80, 20))
        self.r2_time_10.SetMinSize((80, 20))
        self.r2_time_11.SetMinSize((80, 20))
        self.r2_time_12.SetMinSize((80, 20))
        self.r2_time_13.SetMinSize((80, 20))
        self.r2_time_14.SetMinSize((80, 20))
        self.panel_3_copy.SetMinSize((620, 300))
        self.panel_3_copy.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1_copy.SetMinSize((688, 300))
        self.panel_1_copy.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_5_copy_1_copy_copy.SetMinSize((118, 17))
        self.relax_start_r1_1_copy.SetName('hello')
        self.relax_start_r1_1_copy.SetSize(self.relax_start_r1_1_copy.GetBestSize())
        self.label_4_copy_1_copy.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_3_copy.SetMinSize((230, 17))
        self.nmrfreq_value_noe1_copy.SetMinSize((350, 27))
        self.label_2_copy_copy_5_copy.SetMinSize((230, 17))
        self.noe_sat_1_copy.SetMinSize((350, 27))
        self.sat_noe_copy_1_copy.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_copy_2_copy.SetMinSize((230, 17))
        self.noe_sat_err_1_copy.SetMinSize((350, 27))
        self.label_2_copy_copy_1_copy_1_copy.SetMinSize((230, 17))
        self.noe_ref_1_copy.SetMinSize((350, 27))
        self.noe_ref_err_copy_1_copy.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_copy_copy_1_copy.SetMinSize((230, 17))
        self.noe_ref_err_1_copy.SetMinSize((350, 27))
        self.label_2_copy_copy_2_copy_1_copy.SetMinSize((230, 17))
        self.structure_noe1_copy.SetMinSize((350, 27))
        self.ref_noe_copy_1_copy.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_1_copy_1_copy.SetMinSize((230, 34))
        self.unres_noe1_copy.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_1_copy.SetMinSize((230, 17))
        self.res_noe1_copy.SetMinSize((350, 27))
        self.chandir_noe1_copy.SetMinSize((103, 27))
        self.label_5_copy_1_copy_1.SetMinSize((118, 17))
        self.relax_start_noe1_copy.SetName('hello')
        self.relax_start_noe1_copy.SetSize(self.relax_start_noe1_copy.GetBestSize())
        self.label_4_copy_copy_copy_1.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_2_copy_copy_2.SetMinSize((230, 17))
        self.nmrfreq_value_r11_copy.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_copy_copy_1.SetMinSize((230, 17))
        self.resultsdir_r11_copy.SetMinSize((350, 27))
        self.results_directory_copy_copy_copy_1.SetMinSize((103, 27))
        self.structure_file_copy_1.SetMinSize((230, 17))
        self.structure_r11_copy.SetMinSize((350, 27))
        self.results_directory_copy_copy_copy_copy.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_2_copy_copy_copy_1.SetMinSize((230, 17))
        self.unresolved_r11_copy.SetMinSize((350, 27))
        self.panel_2_copy_1.SetMinSize((688, 5))
        self.addr11_copy.SetMinSize((60, 27))
        self.refreshr11_copy.SetMinSize((60, 27))
        self.label_3_copy_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6_copy_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.r1_time_1_copy.SetMinSize((80, 20))
        self.r1_time_2_copy.SetMinSize((80, 20))
        self.r1_time_3_copy.SetMinSize((80, 20))
        self.r1_time_4_copy.SetMinSize((80, 20))
        self.r1_time_5_copy.SetMinSize((80, 20))
        self.r1_time_6_copy.SetMinSize((80, 20))
        self.r1_time_7_copy.SetMinSize((80, 20))
        self.r1_time_8_copy.SetMinSize((80, 20))
        self.r1_time_9_copy.SetMinSize((80, 20))
        self.r1_time_10_copy.SetMinSize((80, 20))
        self.r1_time_11_copy.SetMinSize((80, 20))
        self.r1_time_12_copy.SetMinSize((80, 20))
        self.r1_time_13_copy.SetMinSize((80, 20))
        self.r1_time_1_4_copy.SetMinSize((80, 20))
        self.panel_3_copy_1.SetMinSize((620, 300))
        self.panel_3_copy_1.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1_copy_1.SetMinSize((688, 300))
        self.panel_1_copy_1.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_5_copy_1_copy_copy_1.SetMinSize((118, 17))
        self.relax_start_r1_1_copy_1.SetName('hello')
        self.relax_start_r1_1_copy_1.SetSize(self.relax_start_r1_1_copy_1.GetBestSize())
        self.label_4_copy_copy_copy_copy.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_2_copy_copy_1_copy.SetMinSize((230, 17))
        self.nmrfreq_value_r21_copy.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_copy_copy_copy.SetMinSize((230, 17))
        self.resultsdir_r21_copy.SetMinSize((350, 27))
        self.results_directory_r21_copy.SetMinSize((103, 27))
        self.structure_file_copy_copy.SetMinSize((230, 17))
        self.structure_r21_copy.SetMinSize((350, 27))
        self.chan_struc_r21_copy.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_2_copy_copy_copy_copy.SetMinSize((230, 17))
        self.unresolved_r21_copy.SetMinSize((350, 27))
        self.panel_2_copy_copy.SetMinSize((688, 5))
        self.addr21_copy.SetMinSize((60, 27))
        self.refreshr21_copy.SetMinSize((60, 27))
        self.label_3_copy_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6_copy_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.r2_time_1_copy.SetMinSize((80, 20))
        self.r2_time_2_copy.SetMinSize((80, 20))
        self.r2_time_3_copy.SetMinSize((80, 20))
        self.r2_time_4_copy.SetMinSize((80, 20))
        self.r2_time_5_copy.SetMinSize((80, 20))
        self.r2_time_6_copy.SetMinSize((80, 20))
        self.r2_time_7_copy.SetMinSize((80, 20))
        self.r2_time_8_copy.SetMinSize((80, 20))
        self.r2_time_9_copy.SetMinSize((80, 20))
        self.r2_time_10_copy.SetMinSize((80, 20))
        self.r2_time_11_copy.SetMinSize((80, 20))
        self.r2_time_12_copy.SetMinSize((80, 20))
        self.r2_time_13_copy.SetMinSize((80, 20))
        self.r2_time_14_copy.SetMinSize((80, 20))
        self.panel_3_copy_copy.SetMinSize((620, 300))
        self.panel_3_copy_copy.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1_copy_copy.SetMinSize((688, 300))
        self.panel_1_copy_copy.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_5_copy_1_copy_copy_copy.SetMinSize((118, 17))
        self.relax_start_r1_1_copy_copy.SetName('hello')
        self.relax_start_r1_1_copy_copy.SetSize(self.relax_start_r1_1_copy_copy.GetBestSize())
        self.label_4_copy_1_copy_1.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_3_copy_1.SetMinSize((230, 17))
        self.nmrfreq_value_noe1_copy_1.SetMinSize((350, 27))
        self.label_2_copy_copy_5_copy_1.SetMinSize((230, 17))
        self.noe_sat_1_copy_1.SetMinSize((350, 27))
        self.sat_noe_copy_1_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_copy_2_copy_1.SetMinSize((230, 17))
        self.noe_sat_err_1_copy_1.SetMinSize((350, 27))
        self.label_2_copy_copy_1_copy_1_copy_1.SetMinSize((230, 17))
        self.noe_ref_1_copy_1.SetMinSize((350, 27))
        self.noe_ref_err_copy_1_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_copy_copy_1_copy_1.SetMinSize((230, 17))
        self.noe_ref_err_1_copy_1.SetMinSize((350, 27))
        self.label_2_copy_copy_2_copy_1_copy_1.SetMinSize((230, 17))
        self.structure_noe1_copy_1.SetMinSize((350, 27))
        self.ref_noe_copy_1_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_1_copy_1_copy_1.SetMinSize((230, 34))
        self.unres_noe1_copy_1.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_1_copy_1.SetMinSize((230, 17))
        self.res_noe1_copy_1.SetMinSize((350, 27))
        self.chandir_noe1_copy_1.SetMinSize((103, 27))
        self.label_5_copy_1_copy_2.SetMinSize((118, 17))
        self.relax_start_noe1_copy_1.SetName('hello')
        self.relax_start_noe1_copy_1.SetSize(self.relax_start_noe1_copy_1.GetBestSize())
        self.label_4_copy_copy_copy_2.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_2_copy_copy_3.SetMinSize((230, 17))
        self.nmrfreq_value_r11_copy_1.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_copy_copy_2.SetMinSize((230, 17))
        self.resultsdir_r11_copy_1.SetMinSize((350, 27))
        self.results_directory_copy_copy_copy_2.SetMinSize((103, 27))
        self.structure_file_copy_2.SetMinSize((230, 17))
        self.structure_r11_copy_1.SetMinSize((350, 27))
        self.results_directory_copy_copy_copy_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_2_copy_copy_copy_2.SetMinSize((230, 17))
        self.unresolved_r11_copy_1.SetMinSize((350, 27))
        self.panel_2_copy_2.SetMinSize((688, 5))
        self.addr11_copy_1.SetMinSize((60, 27))
        self.refreshr11_copy_1.SetMinSize((60, 27))
        self.label_3_copy_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6_copy_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.r1_time_1_copy_1.SetMinSize((80, 20))
        self.r1_time_2_copy_1.SetMinSize((80, 20))
        self.r1_time_3_copy_1.SetMinSize((80, 20))
        self.r1_time_4_copy_1.SetMinSize((80, 20))
        self.r1_time_5_copy_1.SetMinSize((80, 20))
        self.r1_time_6_copy_1.SetMinSize((80, 20))
        self.r1_time_7_copy_1.SetMinSize((80, 20))
        self.r1_time_8_copy_1.SetMinSize((80, 20))
        self.r1_time_9_copy_1.SetMinSize((80, 20))
        self.r1_time_10_copy_1.SetMinSize((80, 20))
        self.r1_time_11_copy_1.SetMinSize((80, 20))
        self.r1_time_12_copy_1.SetMinSize((80, 20))
        self.r1_time_13_copy_1.SetMinSize((80, 20))
        self.r1_time_1_4_copy_1.SetMinSize((80, 20))
        self.panel_3_copy_2.SetMinSize((620, 300))
        self.panel_3_copy_2.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1_copy_2.SetMinSize((688, 300))
        self.panel_1_copy_2.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_5_copy_1_copy_copy_2.SetMinSize((118, 17))
        self.relax_start_r1_1_copy_2.SetName('hello')
        self.relax_start_r1_1_copy_2.SetSize(self.relax_start_r1_1_copy_2.GetBestSize())
        self.label_4_copy_copy_copy_copy_1.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2_copy_copy_copy_2_copy_copy_1_copy_1.SetMinSize((230, 17))
        self.nmrfreq_value_r21_copy_1.SetMinSize((350, 27))
        self.label_2_copy_copy_3_copy_copy_copy_copy_1.SetMinSize((230, 17))
        self.resultsdir_r21_copy_1.SetMinSize((350, 27))
        self.results_directory_r21_copy_1.SetMinSize((103, 27))
        self.structure_file_copy_copy_1.SetMinSize((230, 17))
        self.structure_r21_copy_1.SetMinSize((350, 27))
        self.chan_struc_r21_copy_1.SetMinSize((103, 27))
        self.label_2_copy_copy_copy_2_copy_copy_copy_copy_1.SetMinSize((230, 17))
        self.unresolved_r21_copy_1.SetMinSize((350, 27))
        self.panel_2_copy_copy_1.SetMinSize((688, 5))
        self.addr21_copy_1.SetMinSize((60, 27))
        self.refreshr21_copy_1.SetMinSize((60, 27))
        self.label_3_copy_copy_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6_copy_copy_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.r2_time_1_copy_1.SetMinSize((80, 20))
        self.r2_time_2_copy_1.SetMinSize((80, 20))
        self.r2_time_3_copy_1.SetMinSize((80, 20))
        self.r2_time_4_copy_1.SetMinSize((80, 20))
        self.r2_time_5_copy_1.SetMinSize((80, 20))
        self.r2_time_6_copy_1.SetMinSize((80, 20))
        self.r2_time_7_copy_1.SetMinSize((80, 20))
        self.r2_time_8_copy_1.SetMinSize((80, 20))
        self.r2_time_9_copy_1.SetMinSize((80, 20))
        self.r2_time_10_copy_1.SetMinSize((80, 20))
        self.r2_time_11_copy_1.SetMinSize((80, 20))
        self.r2_time_12_copy_1.SetMinSize((80, 20))
        self.r2_time_13_copy_1.SetMinSize((80, 20))
        self.r2_time_14_copy_1.SetMinSize((80, 20))
        self.panel_3_copy_copy_1.SetMinSize((620, 300))
        self.panel_3_copy_copy_1.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.panel_1_copy_copy_1.SetMinSize((688, 300))
        self.panel_1_copy_copy_1.SetBackgroundColour(wx.Colour(192, 192, 192))
        self.label_5_copy_1_copy_copy_copy_1.SetMinSize((118, 17))
        self.relax_start_r1_1_copy_copy_1.SetName('hello')
        self.relax_start_r1_1_copy_copy_1.SetSize(self.relax_start_r1_1_copy_copy_1.GetBestSize())


    def add_r1_1(self, event): # add a r1 peak list

        if len(r1_list) < 14:
            r1_entry = multi_openfile('Select R1 peak list file', self.resultsdir_r11_copy.GetValue(), '*.*', 'all files (*.*)|*.*')
            if not r1_entry == None:
                r1_list.append(r1_entry)

        if len(r1_list) >= 1:
            self.r1_list_1.SetLabel(r1_list[0])
        if len(r1_list) >= 2:
            self.r1_list_2.SetLabel(r1_list[1])
        if len(r1_list) >= 3:
            self.r1_list_3.SetLabel(r1_list[2])
        if len(r1_list) >= 4:
            self.r1_list_4.SetLabel(r1_list[3])
        if len(r1_list) >= 5:
            self.r1_list_5.SetLabel(r1_list[4])
        if len(r1_list) >= 6:
            self.r1_list_6.SetLabel(r1_list[5])
        if len(r1_list) >= 7:
            self.r1_list_7.SetLabel(r1_list[6])
        if len(r1_list) >= 8:
            self.r1_list_8.SetLabel(r1_list[7])
        if len(r1_list) >= 9:
            self.r1_list_9.SetLabel(r1_list[8])
        if len(r1_list) >= 10:
            self.r1_list_10.SetLabel(r1_list[9])
        if len(r1_list) >= 11:
            self.r1_list_11.SetLabel(r1_list[10])
        if len(r1_list) >= 12:
            self.r1_list_12.SetLabel(r1_list[11])
        if len(r1_list) >= 13:
            self.r1_list_1_copy_11.SetLabel(r1_list[12])
        if len(r1_list) >= 14:
            self.r1_list_14.SetLabel(r1_list[13])
        event.Skip()


    def exec_r1_1(self, event): # start r2 calculation
        relax_times_r2_1 = [0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        #create relaxation time list
        relax_times_r2_1[0] = str(self.r2_time_1.GetValue())
        relax_times_r2_1[1] = str(self.r2_time_2.GetValue())
        relax_times_r2_1[2] = str(self.r2_time_3.GetValue())
        relax_times_r2_1[3] = str(self.r2_time_4.GetValue())
        relax_times_r2_1[4] = str(self.r2_time_5.GetValue())
        relax_times_r2_1[5] = str(self.r2_time_6.GetValue())
        relax_times_r2_1[6] = str(self.r2_time_7.GetValue())
        relax_times_r2_1[7] = str(self.r2_time_8.GetValue())
        relax_times_r2_1[8] = str(self.r2_time_9.GetValue())
        relax_times_r2_1[9] = str(self.r2_time_10.GetValue())
        relax_times_r2_1[10] = str(self.r2_time_11.GetValue())
        relax_times_r2_1[11] = str(self.r2_time_12.GetValue())
        relax_times_r2_1[12] = str(self.r2_time_13.GetValue())
        relax_times_r2_1[13] = str(self.r2_time_14.GetValue())
        start_relax = exec_relax()
        if start_relax == True:
            start_rx(self.resultsdir_r21.GetValue(), r2_list, relax_times_r2_1, self.structure_r11.GetValue(), self.nmrfreq_value_r11.GetValue(), 2, 1, self.unresolved_r11.GetValue(), self, 1, global_setting, file_setting, sequencefile)
        event.Skip()


    def refresh_r1_1(self, event): # refresh r1 list no. 1
        self.r1_list_1.SetLabel('')
        self.r1_list_2.SetLabel('')
        self.r1_list_3.SetLabel('')
        self.r1_list_4.SetLabel('')
        self.r1_list_5.SetLabel('')
        self.r1_list_6.SetLabel('')
        self.r1_list_7.SetLabel('')
        self.r1_list_8.SetLabel('')
        self.r1_list_9.SetLabel('')
        self.r1_list_10.SetLabel('')
        self.r1_list_11.SetLabel('')
        self.r1_list_12.SetLabel('')
        self.r1_list_1_copy_11.SetLabel('')
        self.r1_list_14.SetLabel('')
        del r1_list[0:len(r1_list)]
        event.Skip()


    def resdir_r1_1(self, event): # R1 results dir 1
        backup = self.resultsdir_r11.GetValue()
        r1_savedir[0] = opendir('Select results directory', default=self.resultsdir_r11.GetValue())
        if r1_savedir[0] == None:
            r1_savedir[0] = backup
        self.resultsdir_r11.SetValue(r1_savedir[0])

        event.Skip()


    def sync_ds(self, upload=False):
        """Synchronise the rx analysis frame and the relax data store, both ways.

        This method allows the frame information to be uploaded into the relax data store, or for the information in the relax data store to be downloaded by the frame.

        @keyword upload:    A flag which if True will cause the frame to send data to the relax data store.  If False, data will be downloaded from the relax data store to update the frame.
        @type upload:       bool
        """

        # Dummy function (for the time being).
