#! /bin/sh

# Target directory.
DIR='/data/relax/gna/relax_mailing_lists/'

# Log file.
LOG=$DIR'log'
ERR=$DIR'err'

# Get the files.
echo -e "Wget, `date`" >> $LOG 2> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-announce/ >> $LOG 2>> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-commits/ >> $LOG 2>> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-users/ >> $LOG 2>> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-devel/ >> $LOG 2>> $ERR
