#! /bin/sh
###############################################################################
#                                                                             #
# Copyright (C) 2013 Edward d'Auvergne                                        #
#                                                                             #
# This file is part of the program relax (http://www.nmr-relax.com).          #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

# Shell script for backing up the relax mailing lists.
#
# This will download all of the mbox files (as well as the less useful HTML files).  To run this as a cron job, a line such as the following can be added to the crontab (via 'crontab -e'):
#
# 5 0 * * *       /data/relax/gna/backup_mailing_lists > /dev/null 2> /dev/null


# Target directory.
DIR='/data/relax/gna/relax_mailing_lists/'

# Log file.
LOG=$DIR'log'
ERR=$DIR'err'

# Get the files.
echo -e "Wget, `date`" >> $LOG 2> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-announce/ >> $LOG 2>> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-commits/ >> $LOG 2>> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-users/ >> $LOG 2>> $ERR
wget -np -m --no-check-certificate https://mail.gna.org/public/relax-devel/ >> $LOG 2>> $ERR
