#! /bin/sh
###############################################################################
#                                                                             #
# Copyright (C) 2014 Edward d'Auvergne                                        #
#                                                                             #
# This file is part of the program relax (http://www.nmr-relax.com).          #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################


# Fetch the files.
curl -O http://ftp.de.debian.org/debian/pool/main/l/latex2html/latex2html_2008-debian1-10.debian.tar.gz
curl -O http://ftp.de.debian.org/debian/pool/main/l/latex2html/latex2html_2008-debian1.orig.tar.gz

# Cleanup.
rm -rf build debian latex2html-2008-debian1

# Unpack the files.
tar xvf latex2html_2008-debian1-10.debian.tar.gz
tar xvf latex2html_2008-debian1.orig.tar.gz

# The build directory.
mv latex2html-2008-debian1 build

# Go there.
cd build

# Patching.
#patch -p1 < ../debian/patches/add-url.patch    # Useless patch as this new URL is dead!
patch -p1 < ../debian/patches/pstoimg-dont-use-rgb-txt.patch
patch -p1 < ../debian/patches/pstoimg-fix-borders.patch
patch -p1 < ../debian/patches/pstoimg-fix-file-pattern.patch
patch -p1 < ../debian/patches/fix-typos.patch
patch -p1 < ../debian/patches/html-version-4.patch
patch -p1 < ../debian/patches/l2hconf-fix-shebang.patch
patch -p1 < ../debian/patches/latex2html-fix-authoraddress.patch
patch -p1 < ../debian/patches/override-dvips-dot-in-filename-problem.patch
patch -p1 < ../debian/patches/manual-fix-address.patch
patch -p1 < ../debian/patches/makefiles-fixes.patch
patch -p1 < ../debian/patches/fix-image-types.patch
patch -p1 < ../debian/patches/add-abnt.patch
patch -p1 < ../debian/patches/fix-romanian.patch
patch -p1 < ../debian/patches/fix-mathend-mark.patch
patch -p1 < ../debian/patches/add-floatflt-ins.patch
patch -p1 < ../debian/patches/fix-pdfoutput.patch
patch -p1 < ../debian/patches/fix-gs-stderr.patch
patch -p1 < ../debian/patches/debian-install.patch
patch -p1 < ../debian/patches/pstoimg-match-gray.patch
patch -p1 < ../debian/patches/fix-spaces-in-filenames.patch
patch -p1 < ../debian/patches/manpages.patch
patch -p1 < ../debian/patches/eurosym.patch
patch -p1 < ../debian/patches/match-multiline.patch
patch -p1 < ../debian/patches/latex2html-fix-defined.patch
patch -p1 < ../relax_lstlisting.patch
patch -p1 < ../relax_max_char.patch
patch -p1 < ../relax_no_generic_words.patch

# Configure.
./configure --prefix=/usr/local
#GS_LIB=/usr/share/ghostscript/9.14/:. ./configure --prefix=/usr/local

# Make.
make
#GS_LIB=/usr/share/ghostscript/9.14/Resource/Init/:/usr/share/ghostscript/9.14/Resource/Font:. make
