#! /usr/bin/python

# Script for getting the relax version.

from os import popen2


class Package:
    def __init__(self):
        """Script for packaging relax into a .tar.bz2 archive."""

        # Get the version string.
        self.get_version()

        # Place the version number into a file.
        file = open('relax_version.tex', 'w')
        file.write("Version " + self.version + '\n')
        file.close()


    def get_version(self):
        """Function for getting the relax version."""

        # Get the program version number printout.
        stdin, stdout = popen2('../../relax -v')
        output = stdout.readline()

        # Close the pipes.
        stdin.close()
        stdout.close()

        # Version number.
        self.version = output[6:-1]

        # Print out.
        print "Version number: " + self.version


if __name__ == '__main__':
    Package()
