###############################################################################
#                                                                             #
# Copyright (C) 2008 Edward d'Auvergne                                        #
#                                                                             #
# This file is part of the program relax.                                     #
#                                                                             #
# relax is free software; you can redistribute it and/or modify               #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation; either version 2 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# relax is distributed in the hope that it will be useful,                    #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with relax; if not, write to the Free Software                        #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA   #
#                                                                             #
###############################################################################

# Python module imports.
import sys
from unittest import TextTestRunner
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO


class RelaxTestRunner(TextTestRunner):
    """A replacement unittest runner.

    This runner is designed to catch STDOUT during the execution of each test and to prepend the
    output to the failure and error reports normally generated by TextTestRunner.
    """

    def run(self, test):
        """Override of the TextTestRunner.run() method."""

        # Catch stdout.
        buf = StringIO()
        sys.stdout = buf

        # Execute the normal run method.
        result = TextTestRunner.run(self, test)

        # Restore stdout.
        sys.stdout = sys.__stdout__

        #print "\n\n\n\n\n\n\n"
        #print dir(results)
        #print "\n\n"
        #print results.failures
        #print `buf.getvalue()`

        # Close the buffer.
        buf.close()

        # Return the results object.
        return result
